[package]
name = "kernel-rsa-pss-device"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
logic = { path = "../../../logic", default-features = false, features = ["rsa-pss"] }
cuda_std = { git = "https://github.com/brandonros/Rust-CUDA.git", rev = "f554f74a78a1ee30b2668f0ec2e5b1fd54b7b588" }

# Device compilation is a separate Cargo invocation and target.
[workspace]

[patch.crates-io]
zeroize = { git = "https://github.com/brandonros/utils", rev = "4c9734e1ae4a6cb61db4693f9d164866f084ca97" }

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
