# Kernels use nightly features and the built-in nvptx64 target.
[toolchain]
channel = "nightly-2026-09-22"
profile = "minimal"
components = ["rust-src", "llvm-tools", "llvm-bitcode-linker", "clippy", "rustfmt"]
targets = ["nvptx64-nvidia-cuda"]
