[package]
name = "logic"
version = "0.1.0"
edition = "2024"

[features]
default = ["shallenge"]
solana = ["dep:curve25519-dalek"]
bitcoin = ["dep:k256"]
ethereum = ["dep:k256", "dep:tiny-keccak"]
shallenge = []
compiler-probes = []
p256-public-key = ["dep:p256", "dep:hmac", "dep:digest"]
p256-signature = ["dep:rfc6979", "dep:p256", "p256/ecdsa", "dep:ecdsa", "dep:hmac", "dep:digest"]
rsa-pss = [ "dep:digest", "dep:crypto-bigint"]
rsa-modulus = [ "dep:digest", "dep:hmac", "dep:crypto-bigint"]
self_test = [
    "self_test_solana",
    "self_test_bitcoin",
    "self_test_ethereum",
    "self_test_shallenge",
    "self_test_p256_public_key",
    "self_test_p256_signature",
    "self_test_rsa_pss",
    "self_test_rsa_modulus",
]
self_test_support = ["dep:paste"]
self_test_metal_entries = ["self_test_support"]
self_test_solana = ["self_test_support", "solana"]
self_test_bitcoin = ["self_test_support", "bitcoin"]
self_test_ethereum = ["self_test_support", "ethereum"]
self_test_shallenge = ["self_test_support", "shallenge"]
self_test_p256_public_key = ["self_test_support", "p256-public-key"]
self_test_p256_signature = ["self_test_support", "p256-signature"]
self_test_rsa_pss = ["self_test_support", "rsa-pss"]
self_test_rsa_modulus = ["self_test_support", "rsa-modulus"]

[dependencies]
rfc6979 = { version = "0.4.0", default-features = false, optional = true }
paste = { version = "1.0", optional = true }
crypto-bigint = { path = "../../vendor/crypto-bigint", version = "0.5.5", default-features = false, features = ["zeroize"], optional = true }
ecdsa = { version = "0.16.9", default-features = false, features = ["hazmat"], optional = true }
hmac = { version = "0.12.1", default-features = false, optional = true }
digest = { version = "0.10.7", default-features = false, features = ["core-api"], optional = true }
zeroize = { version = "1", default-features = false }
p256 = { version = "0.13.2", default-features = false, features = ["arithmetic"], optional = true }
curve25519-dalek = { version = "4.1.3", default-features = false, features = ["alloc", "precomputed-tables"], optional = true }
k256 = { version = "0.13.4", default-features = false, features = ["alloc", "arithmetic", "precomputed-tables", "critical-section"], optional = true }
tiny-keccak = { version = "2.0", default-features = false, features = ["keccak"], optional = true }
rand_core = { version = "0.9.3", default-features = false }
rand_xoshiro = { version = "0.7.0", default-features = false }
seq-macro = "0.3"
hex = { version = "0.4.3", default-features = false, features = ["alloc"] }
