use super::Case;

pub const CASES: &[Case] = &[
    Case {
        slot: 4,
        label: "secp256k1 compressed",
        kernel: "kernel_self_test_bitcoin",
        gpu_skip: None,
    },
    Case {
        slot: 7,
        label: "ripemd160 32bytes",
        kernel: "kernel_self_test_bitcoin",
        gpu_skip: None,
    },
    Case {
        slot: 8,
        label: "sha256 32bytes",
        kernel: "kernel_self_test_bitcoin",
        gpu_skip: None,
    },
    Case {
        slot: 16,
        label: "bitcoin priv",
        kernel: "kernel_self_test_bitcoin",
        gpu_skip: None,
    },
    Case {
        slot: 17,
        label: "bitcoin pub",
        kernel: "kernel_self_test_bitcoin",
        gpu_skip: None,
    },
    Case {
        slot: 18,
        label: "bitcoin pkh",
        kernel: "kernel_self_test_bitcoin",
        gpu_skip: None,
    },
    Case {
        slot: 19,
        label: "bitcoin encoded",
        kernel: "kernel_self_test_bitcoin",
        gpu_skip: None,
    },
    Case {
        slot: 20,
        label: "bitcoin matches",
        kernel: "kernel_self_test_bitcoin",
        gpu_skip: None,
    },
    Case {
        slot: 21,
        label: "wif compressed mainnet",
        kernel: "kernel_self_test_bitcoin",
        gpu_skip: None,
    },
    Case {
        slot: 22,
        label: "wif uncompressed mainnet",
        kernel: "kernel_self_test_bitcoin",
        gpu_skip: None,
    },
    Case {
        slot: 23,
        label: "wif compressed testnet",
        kernel: "kernel_self_test_bitcoin",
        gpu_skip: None,
    },
    Case {
        slot: 24,
        label: "wif uncompressed testnet",
        kernel: "kernel_self_test_bitcoin",
        gpu_skip: None,
    },
    Case {
        slot: 42,
        label: "base58 var-len leading-zero",
        kernel: "kernel_self_test_bitcoin",
        gpu_skip: None,
    },
    Case {
        slot: 45,
        label: "bech32 p2wpkh",
        kernel: "kernel_self_test_bitcoin",
        gpu_skip: None,
    },
    Case {
        slot: 73,
        label: "k256 SecretKey::from_bytes(1)",
        kernel: "kernel_self_test_bitcoin",
        gpu_skip: None,
    },
    Case {
        slot: 74,
        label: "k256 derive scalar=1 == generator",
        kernel: "kernel_self_test_bitcoin",
        gpu_skip: None,
    },
    Case {
        slot: 75,
        label: "k256 derive scalar=2 == 2G",
        kernel: "kernel_self_test_bitcoin",
        gpu_skip: None,
    },
    Case {
        slot: 76,
        label: "static [u64; 5] indexed read",
        kernel: "kernel_self_test_bitcoin",
        gpu_skip: None,
    },
    Case {
        slot: 77,
        label: "static struct-wrapped [u64; 5] indexed read",
        kernel: "kernel_self_test_bitcoin",
        gpu_skip: None,
    },
    Case {
        slot: 78,
        label: "k256 encode generator (no mul)",
        kernel: "kernel_self_test_bitcoin",
        gpu_skip: None,
    },
    Case {
        slot: 79,
        label: "k256 double generator + encode",
        kernel: "kernel_self_test_bitcoin",
        gpu_skip: None,
    },
    Case {
        slot: 80,
        label: "k256 Scalar::ONE round-trip",
        kernel: "kernel_self_test_bitcoin",
        gpu_skip: None,
    },
    Case {
        slot: 93,
        label: "k256 AffinePoint::GENERATOR.to_encoded_point()",
        kernel: "kernel_self_test_bitcoin",
        gpu_skip: None,
    },
    Case {
        slot: 94,
        label: "subtle Choice from(u8) into bool",
        kernel: "kernel_self_test_bitcoin",
        gpu_skip: None,
    },
    Case {
        slot: 95,
        label: "subtle u64::conditional_select(0|1)",
        kernel: "kernel_self_test_bitcoin",
        gpu_skip: None,
    },
    Case {
        slot: 96,
        label: "k256 EncodedPoint::from_affine_coordinates(GX, GY)",
        kernel: "kernel_self_test_bitcoin",
        gpu_skip: None,
    },
    Case {
        slot: 97,
        label: "Index trait const-idx (5 writes/reads)",
        kernel: "kernel_self_test_bitcoin",
        gpu_skip: None,
    },
    Case {
        slot: 98,
        label: "GenericArray<u8, U33> basic index",
        kernel: "kernel_self_test_bitcoin",
        gpu_skip: None,
    },
    Case {
        slot: 99,
        label: "GenericArray<u8, U33> copy_from_slice",
        kernel: "kernel_self_test_bitcoin",
        gpu_skip: None,
    },
    Case {
        slot: 100,
        label: "k256 from_affine_coords replica (raw [u8; 33])",
        kernel: "kernel_self_test_bitcoin",
        gpu_skip: None,
    },
    Case {
        slot: 101,
        label: "GenericArray y.as_slice().last() shape",
        kernel: "kernel_self_test_bitcoin",
        gpu_skip: None,
    },
    Case {
        slot: 104,
        label: "k256 (&[u8; 32]).into() &FieldBytes",
        kernel: "kernel_self_test_bitcoin",
        gpu_skip: None,
    },
    Case {
        slot: 110,
        label: "GenericArray dst.copy_from_slice(src GA)",
        kernel: "kernel_self_test_bitcoin",
        gpu_skip: None,
    },
];
