[package]
name = "kernel-p256-public-key"
version = "0.1.0"
edition = "2024"

# Builds p256_public_key.ptx.
[lib]
name = "p256_public_key"
crate-type = ["cdylib"]

[dependencies]
kernel-common = { path = "../common" }
logic = { path = "../../logic", default-features = false, features = ["p256-public-key"] }
