[package]
name = "kernel-self-test-p256-signature"
version = "0.1.0"
edition = "2024"

# Builds self_test_p256_signature.ptx.
[lib]
name = "self_test_p256_signature"
crate-type = ["cdylib"]

[dependencies]
kernel-common = { path = "../common" }
logic = { path = "../../logic", default-features = false, features = ["self_test_p256_signature"] }
