[package]
name = "kernels"
version = "0.1.0"
edition = "2024"

[features]
default = ["kernel_shallenge"]
kernel_bitcoin = ["logic/bitcoin"]
kernel_ethereum = ["logic/ethereum"]
kernel_solana = ["logic/solana"]
kernel_shallenge = ["logic/shallenge"]
kernel_self_test = ["logic/self_test"]

[dependencies]
logic = { path = "../logic", default-features = false }
cuda-device = { workspace = true }
cuda-host = { workspace = true }
cuda-core = { workspace = true }
