[package]
name = "kernels"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["shallenge"]
solana = ["logic/solana"]
bitcoin = ["logic/bitcoin"]
ethereum = ["logic/ethereum"]
shallenge = ["logic/shallenge"]
self_test = ["logic/self_test"]
rsa-modulus = ["logic/rsa-modulus"]
rsa-pss = ["logic/rsa-pss"]
p256-public-key = ["logic/p256-public-key"]
p256-signature = ["logic/p256-signature"]

[dependencies]
logic = { path = "../logic", default-features = false }
cuda_std = { git = "https://github.com/brandonros/Rust-CUDA.git", rev = "d2104a0a49252068292985e5e63328f522415c4b" }

[workspace]

[patch.crates-io]
zeroize = { git = "https://github.com/brandonros/utils", rev = "4c9734e1ae4a6cb61db4693f9d164866f084ca97" }

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
