[package]
name = "kernel-self-test-rsa-modulus"
version = "0.1.0"
edition = "2024"

# Builds self_test_rsa_modulus.ptx.
[lib]
name = "self_test_rsa_modulus"
crate-type = ["cdylib"]

[dependencies]
kernel-common = { path = "../common" }
logic = { path = "../../logic", default-features = false, features = ["self_test_rsa_modulus"] }
