[package]
name = "kernel-self-test-ethereum"
version = "0.1.0"
edition = "2024"

# Builds self_test_ethereum.ptx.
[lib]
name = "self_test_ethereum"
crate-type = ["cdylib"]

[dependencies]
kernel-common = { path = "../common" }
logic = { path = "../../logic", default-features = false, features = ["self_test_ethereum"] }
