[package]
name = "kernel-self-test-shallenge"
version = "0.1.0"
edition = "2024"

# Builds self_test_shallenge.ptx.
[lib]
name = "self_test_shallenge"
crate-type = ["cdylib"]

[dependencies]
kernel-common = { path = "../common" }
logic = { path = "../../logic", default-features = false, features = ["self_test_shallenge"] }
