use super::Case;

pub const CASES: &[Case] = &[
    Case {
        slot: 0,
        label: "xoroshiro priv",
        kernel: "kernel_self_test_solana",
        gpu_skip: None,
    },
    Case {
        slot: 1,
        label: "sha512 of priv",
        kernel: "kernel_self_test_solana",
        gpu_skip: None,
    },
    Case {
        slot: 2,
        label: "ed25519 derive",
        kernel: "kernel_self_test_solana",
        gpu_skip: None,
    },
    Case {
        slot: 3,
        label: "base58 encode pub",
        kernel: "kernel_self_test_solana",
        gpu_skip: None,
    },
    Case {
        slot: 10,
        label: "solana priv",
        kernel: "kernel_self_test_solana",
        gpu_skip: None,
    },
    Case {
        slot: 11,
        label: "solana pub",
        kernel: "kernel_self_test_solana",
        gpu_skip: None,
    },
    Case {
        slot: 12,
        label: "solana encoded",
        kernel: "kernel_self_test_solana",
        gpu_skip: None,
    },
    Case {
        slot: 31,
        label: "arith u32 div var",
        kernel: "kernel_self_test_solana",
        gpu_skip: None,
    },
    Case {
        slot: 32,
        label: "arith u32 div const",
        kernel: "kernel_self_test_solana",
        gpu_skip: None,
    },
    Case {
        slot: 33,
        label: "arith u64 div var",
        kernel: "kernel_self_test_solana",
        gpu_skip: None,
    },
    Case {
        slot: 34,
        label: "arith u64 div const",
        kernel: "kernel_self_test_solana",
        gpu_skip: None,
    },
    Case {
        slot: 35,
        label: "arith u32 rem var",
        kernel: "kernel_self_test_solana",
        gpu_skip: None,
    },
    Case {
        slot: 36,
        label: "arith u64 rem var",
        kernel: "kernel_self_test_solana",
        gpu_skip: None,
    },
    Case {
        slot: 37,
        label: "arith u32 mul lo",
        kernel: "kernel_self_test_solana",
        gpu_skip: None,
    },
    Case {
        slot: 38,
        label: "arith u64 mul lo",
        kernel: "kernel_self_test_solana",
        gpu_skip: None,
    },
    Case {
        slot: 39,
        label: "arith u64 mul hi",
        kernel: "kernel_self_test_solana",
        gpu_skip: None,
    },
    Case {
        slot: 40,
        label: "arith u128 mul",
        kernel: "kernel_self_test_solana",
        gpu_skip: None,
    },
    Case {
        slot: 41,
        label: "base58 var-len",
        kernel: "kernel_self_test_solana",
        gpu_skip: None,
    },
    Case {
        slot: 43,
        label: "base58 32 all-zeros",
        kernel: "kernel_self_test_solana",
        gpu_skip: None,
    },
    Case {
        slot: 46,
        label: "arith overflowing_add",
        kernel: "kernel_self_test_solana",
        gpu_skip: None,
    },
    Case {
        slot: 47,
        label: "arith overflowing_sub",
        kernel: "kernel_self_test_solana",
        gpu_skip: None,
    },
    Case {
        slot: 48,
        label: "arith carry-chain 3limb",
        kernel: "kernel_self_test_solana",
        gpu_skip: None,
    },
    Case {
        slot: 49,
        label: "arith widening mul pair",
        kernel: "kernel_self_test_solana",
        gpu_skip: None,
    },
    Case {
        slot: 50,
        label: "arith mad lo u64",
        kernel: "kernel_self_test_solana",
        gpu_skip: None,
    },
    Case {
        slot: 51,
        label: "arith mad hi u64",
        kernel: "kernel_self_test_solana",
        gpu_skip: None,
    },
    Case {
        slot: 52,
        label: "arith mul wide u32",
        kernel: "kernel_self_test_solana",
        gpu_skip: None,
    },
    Case {
        slot: 53,
        label: "arith mask blend true",
        kernel: "kernel_self_test_solana",
        gpu_skip: None,
    },
    Case {
        slot: 54,
        label: "arith mask blend false",
        kernel: "kernel_self_test_solana",
        gpu_skip: None,
    },
    Case {
        slot: 55,
        label: "arith var shr u64",
        kernel: "kernel_self_test_solana",
        gpu_skip: None,
    },
    Case {
        slot: 56,
        label: "arith var shl u64",
        kernel: "kernel_self_test_solana",
        gpu_skip: None,
    },
    Case {
        slot: 57,
        label: "arith blackbox identity u64",
        kernel: "kernel_self_test_solana",
        gpu_skip: None,
    },
    Case {
        slot: 58,
        label: "arith blackbox identity u32",
        kernel: "kernel_self_test_solana",
        gpu_skip: None,
    },
    Case {
        slot: 59,
        label: "base58 div by 58",
        kernel: "kernel_self_test_solana",
        gpu_skip: None,
    },
    Case {
        slot: 60,
        label: "iter static table lookup",
        kernel: "kernel_self_test_solana",
        gpu_skip: None,
    },
    Case {
        slot: 61,
        label: "iter mut slice partial",
        kernel: "kernel_self_test_solana",
        gpu_skip: None,
    },
    Case {
        slot: 62,
        label: "iter mut alphabet lookup",
        kernel: "kernel_self_test_solana",
        gpu_skip: None,
    },
    Case {
        slot: 63,
        label: "iter static slice lookup",
        kernel: "kernel_self_test_solana",
        gpu_skip: None,
    },
    Case {
        slot: 64,
        label: "arith divrem by 58^5",
        kernel: "kernel_self_test_solana",
        gpu_skip: None,
    },
    Case {
        slot: 65,
        label: "arith i128 chain add",
        kernel: "kernel_self_test_solana",
        gpu_skip: None,
    },
    Case {
        slot: 66,
        label: "base58 limb divrem (shl+add multiplicand)",
        kernel: "kernel_self_test_solana",
        gpu_skip: None,
    },
    Case {
        slot: 67,
        label: "dynamic-grow stack array write",
        kernel: "kernel_self_test_solana",
        gpu_skip: None,
    },
    Case {
        slot: 68,
        label: "widening mul chain 3-term",
        kernel: "kernel_self_test_solana",
        gpu_skip: None,
    },
    Case {
        slot: 69,
        label: "base58 inner-mutate phase A",
        kernel: "kernel_self_test_solana",
        gpu_skip: None,
    },
    Case {
        slot: 70,
        label: "dalek clamp_integer",
        kernel: "kernel_self_test_solana",
        gpu_skip: None,
    },
    Case {
        slot: 71,
        label: "dalek scalar from-bytes round-trip",
        kernel: "kernel_self_test_solana",
        gpu_skip: None,
    },
    Case {
        slot: 72,
        label: "dalek mul_base scalar=1 == basepoint",
        kernel: "kernel_self_test_solana",
        gpu_skip: None,
    },
    Case {
        slot: 81,
        label: "arith u128 immediate shr 52",
        kernel: "kernel_self_test_solana",
        gpu_skip: None,
    },
    Case {
        slot: 82,
        label: "static depth-4 newtype nesting",
        kernel: "kernel_self_test_solana",
        gpu_skip: None,
    },
    Case {
        slot: 83,
        label: "reverse range iterator write",
        kernel: "kernel_self_test_solana",
        gpu_skip: None,
    },
    Case {
        slot: 84,
        label: "dalek Scalar52::from_bytes(1)",
        kernel: "kernel_self_test_solana",
        gpu_skip: None,
    },
    Case {
        slot: 85,
        label: "dalek Scalar52::from_montgomery(R) == 1",
        kernel: "kernel_self_test_solana",
        gpu_skip: None,
    },
    Case {
        slot: 86,
        label: "dalek Scalar52::ONE.as_montgomery() == R",
        kernel: "kernel_self_test_solana",
        gpu_skip: None,
    },
    Case {
        slot: 87,
        label: "dalek Scalar52([1,..]).as_bytes() == [1,0,..]",
        kernel: "kernel_self_test_solana",
        gpu_skip: None,
    },
    Case {
        slot: 88,
        label: "dalek Scalar52::sub(R, R) == 0 (no underflow)",
        kernel: "kernel_self_test_solana",
        gpu_skip: None,
    },
    Case {
        slot: 89,
        label: "dalek Scalar52::sub(0, 1) underflow path",
        kernel: "kernel_self_test_solana",
        gpu_skip: None,
    },
    Case {
        slot: 90,
        label: "dalek montgomery_reduce(R) with final sub",
        kernel: "kernel_self_test_solana",
        gpu_skip: None,
    },
    Case {
        slot: 91,
        label: "Index/IndexMut trait dispatch",
        kernel: "kernel_self_test_solana",
        gpu_skip: None,
    },
    Case {
        slot: 92,
        label: "dalek Scalar::ONE.to_bytes() direct",
        kernel: "kernel_self_test_solana",
        gpu_skip: None,
    },
    Case {
        slot: 102,
        label: "dalek scalar round-trip ZERO",
        kernel: "kernel_self_test_solana",
        gpu_skip: None,
    },
    Case {
        slot: 103,
        label: "dalek from_bytes_mod_order_wide zero",
        kernel: "kernel_self_test_solana",
        gpu_skip: None,
    },
    Case {
        slot: 105,
        label: "base58 single-nonzero-byte (limb_count=1)",
        kernel: "kernel_self_test_solana",
        gpu_skip: None,
    },
    Case {
        slot: 106,
        label: "named-field struct return (Scalar shape)",
        kernel: "kernel_self_test_solana",
        gpu_skip: None,
    },
    Case {
        slot: 107,
        label: "base58 hand-rolled no-seq! single-nonzero",
        kernel: "kernel_self_test_solana",
        gpu_skip: None,
    },
    Case {
        slot: 108,
        label: "<[u8]>::reverse() partial sub-slice",
        kernel: "kernel_self_test_solana",
        gpu_skip: None,
    },
    Case {
        slot: 109,
        label: "dalek Scalar(0) == Scalar::ZERO (no to_bytes)",
        kernel: "kernel_self_test_solana",
        gpu_skip: None,
    },
    Case {
        slot: 111,
        label: "dalek Scalar::ZERO == Scalar::ZERO (PartialEq)",
        kernel: "kernel_self_test_solana",
        gpu_skip: None,
    },
    Case {
        slot: 112,
        label: "dalek Scalar::from_canonical_bytes(0) == ZERO",
        kernel: "kernel_self_test_solana",
        gpu_skip: None,
    },
    Case {
        slot: 113,
        label: "dalek bisect Scalar52::from_bytes(0)",
        kernel: "kernel_self_test_solana",
        gpu_skip: None,
    },
    Case {
        slot: 114,
        label: "dalek bisect Scalar52::mul_internal(0, R)",
        kernel: "kernel_self_test_solana",
        gpu_skip: None,
    },
    Case {
        slot: 115,
        label: "dalek bisect Scalar52::montgomery_reduce(0)",
        kernel: "kernel_self_test_solana",
        gpu_skip: None,
    },
    Case {
        slot: 116,
        label: "dalek bisect Scalar52::ZERO.as_bytes()",
        kernel: "kernel_self_test_solana",
        gpu_skip: None,
    },
    Case {
        slot: 117,
        label: "dalek bisect full reduce pipeline (zero in)",
        kernel: "kernel_self_test_solana",
        gpu_skip: None,
    },
];
