[package]
name = "kernel-p256-signature"
version = "0.1.0"
edition = "2024"

# Builds p256_signature.ptx.
[lib]
name = "p256_signature"
crate-type = ["cdylib"]

[dependencies]
kernel-common = { path = "../common" }
logic = { path = "../../logic", default-features = false, features = ["p256-signature"] }
