#!/usr/bin/env python3
"""Regenerate hash/scalar/window self-test answers with Python integers and hashlib.

Run with --check to verify checked-in fixtures without modifying them.
No Rust implementation under test is used to compute these answers.
"""
import argparse
import hashlib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1] / 'logic/src/self_test'

def array(name, value):
    rows = [', '.join(f'0x{x:02x}' for x in value[i:i + 12]) + ','
            for i in range(0, len(value), 12)]
    return f'#[rustfmt::skip]\npub(super) const {name}: [u8; {len(value)}] = [\n' + ''.join('    ' + r + '\n' for r in rows) + '];\n'

def fixtures():
    yield 'shallenge/sha256_fixtures.rs', ''.join(array(f'SHA256_{n}_EXPECTED', hashlib.sha256(bytes(range(n))).digest()) for n in [0, 55, 56, 63, 64, 65, 256])
    # Curve parameters agree with the existing generator/order fixtures.
    field = int('ffffffff00000001000000000000000000000000ffffffffffffffffffffffff', 16)
    gx = bytes.fromhex('6b17d1f2e12c4247f8bce6e563a440f277037d812deb33a0f4a13945d898c296')
    gy = int('4fe342e2fe1a7f9b8ee7eb4a7c0f9e162bce33576b315ececbb6406837bf51f5', 16)
    yield 'p256_public_key/scalar_fixtures.rs', array('NEGATIVE_GENERATOR', b'\x04' + gx + (field - gy).to_bytes(32, 'big'))
    order = 2**252 + 27742317777372353535851937790883648493
    yield 'solana/scalar_fixtures.rs', (array('SCALAR_ORDER', order.to_bytes(32, 'little'))
        + array('WIDE_REDUCED', (int.from_bytes(bytes(range(64)), 'little') % order).to_bytes(32, 'little')))
    message = bytearray([0xa5] * 160)
    # A 129-byte window crosses two hash blocks and needs more than one zero-padding update.
    message[7:136] = (0x0102030405060708090a0b0c0d0e0f10).to_bytes(129, 'big')
    yield 'p256_signature/window_fixtures.rs', array('LONG_WINDOW_SHA256', hashlib.sha256(message).digest())

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    for relative, body in fixtures():
        path = ROOT / relative
        content = '// Generated by scripts/self-test-fixtures.py; do not edit by hand.\n' + body
        if args.check:
            if path.read_text() != content:
                raise SystemExit(f'Fixture differs: {path}')
        else:
            path.write_text(content)
