[package]
name = "logic"
version = "0.1.0"
edition = "2024"

[features]
default = ["shallenge"]
solana = ["dep:curve25519-dalek"]
bitcoin = ["dep:k256"]
ethereum = ["dep:k256", "dep:tiny-keccak"]
shallenge = []
p256-public-key = ["dep:p256", "crypto-search"]
p256-signature = ["dep:p256", "p256/ecdsa", "dep:ecdsa", "crypto-search"]
crypto-search = ["dep:hmac", "dep:sha2", "dep:zeroize"]
rsa-pss = ["crypto-search", "dep:crypto-bigint"]
rsa-modulus = ["crypto-search", "dep:crypto-bigint"]
self_test = ["solana", "bitcoin", "ethereum", "shallenge", "p256-public-key", "p256-signature", "rsa-pss", "rsa-modulus"]

[dependencies]
crypto-bigint = { version = "0.5.5", default-features = false, features = ["zeroize"], optional = true }
ecdsa = { version = "0.16.9", default-features = false, features = ["hazmat"], optional = true }
hmac = { version = "0.12.1", default-features = false, optional = true }
sha2 = { version = "0.10.9", default-features = false, optional = true }
zeroize = { version = "1", default-features = false, optional = true }
p256 = { version = "0.13.2", default-features = false, features = ["arithmetic"], optional = true }
curve25519-dalek = { version = "4.1.3", default-features = false, features = ["alloc", "precomputed-tables"], optional = true }
k256 = { version = "0.13.4", default-features = false, features = ["alloc", "arithmetic", "precomputed-tables", "critical-section"], optional = true }
tiny-keccak = { version = "2.0", default-features = false, features = ["keccak"], optional = true }
rand_core = { version = "0.9.3", default-features = false }
rand_xoshiro = { version = "0.7.0", default-features = false }
seq-macro = "0.3"
hex = { version = "0.4.3", default-features = false, features = ["alloc"] }
