[package]
name = "kernel-self-test-p256-public-key"
version = "0.1.0"
edition = "2024"

# Builds self_test_p256_public_key.ptx.
[lib]
name = "self_test_p256_public_key"
crate-type = ["cdylib"]

[dependencies]
kernel-common = { path = "../common" }
logic = { path = "../../logic", default-features = false, features = ["self_test_p256_public_key"] }
