[package]
name = "kernel-shallenge"
version = "0.1.0"
edition = "2024"

[features]
default = ["cuda"]
cuda = ["dep:cuda_builder"]
llvm21 = ["cuda", "cuda_builder/llvm21"]

[build-dependencies.cuda_builder]
git = "https://github.com/brandonros/Rust-CUDA.git"
rev = "c0539920dfdce2b745df87d0d0685d2ffca66b50"
default-features = false
features = ["rustc_codegen_nvvm"]
optional = true
