[package]
name = "kernel-p256-signature"
version = "0.1.0"
edition = "2024"

[features]
default = ["cuda"]
cuda = ["dep:cuda_builder"]
llvm21 = ["cuda", "cuda_builder/llvm21"]

[build-dependencies.cuda_builder]
git = "https://github.com/brandonros/Rust-CUDA.git"
rev = "7c07c618dd7c1c08af4d040a5fc422d9ebf8caff"
default-features = false
features = ["rustc_codegen_nvvm"]
optional = true
